### ISSUE TITLE
web-mode-html-tag-face hard to read

### ISSUE THREAD

**Issue by juliusdelta** [protesilaos/doric-themes#7]
Hello Prot!

I'm very much enjoying `doric-themes`, in particular `doric-light`. 

At my day job I frequently work with HTML & JSX and use `web-mode` when interacting with those files. In the current iteration of `doric-light`(commit https://github.com/protesilaos/doric-themes/commit/fe5a9884005be61609d060b1ecb7530d06e98cdf) HTML tags specifically are hard to read.

![Image](https://github.com/user-attachments/assets/2eb22779-55b8-428c-a8ba-2771cc7c90cf)

The light gray is hard to read on the white background.

I'm very unfamiliar with determining the face of a particular text object (and emacs themes for that matter) but from what I've been able to determine, HTML tags use the `web-mode-html-tag-face`. From the `sample` from the `describe-face` screenshot this appears to be the source:

![Image](https://github.com/user-attachments/assets/4ca25539-f0bf-43de-b464-c69d42873674)

<details>
<summary>Entire describe face entry</summary>

```
Face: web-mode-html-tag-face (sample) (customize this face)

Documentation:
Face for html tags.

Defined in ‘web-mode.el’.
           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: Snow4
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```
</details>

Is this something that Doric themes can be updated to fix?

I assume that particular face (or set of `web-mode` faces) can be added to [one of the face variables here](https://github.com/protesilaos/doric-themes/blob/main/doric-themes.el#L273). If this is the case, I'm more than happy to open a PR to fix. I just wanted to accomplish 2 things by opening this issue:

- Having a good issue tracking history for features/fixes
- Get approval from you on opening a PR for this myself

Thanks!
